### ISSUE TITLE
Generating Veeva Thumbnails issue

### ISSUE THREAD

**Issue by pjoimedia** [devopsgroup-io/veeva#17]
Running "gulp build" returns the following error:

Generating Veeva Thumbnails
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

**Comment by stevebritton** [comment]
pjoimedia,

Few questions:
- What platform did you attempt to run on (windows, osx)? 
- Were you testing the example project that's included in this repo?

Also, I just published a new version this evening, which resolves some bugs related to files not being in place in the example project.

**Comment by stevebritton** [comment]
Two more things:
1. Which version of node and npm are you running?
2. Can you run the build command with the **-V** arg? This will pump out some additional logging.

```
 gulp build -V
```
- Steve
