### ISSUE TITLE
veeva-deploy not doing anything 

### ISSUE THREAD

**Issue by YannickGagnon** [devopsgroup-io/veeva#34]
Hi,

I just installed veeva and tried it with provided example project. Even though the script reports:

[13:40:53] Starting 'veeva-deploy'...
NOTE ⤷ Deploying zipped files
NOTE ⤷ Deploying control files
✔︎ Done Deploying Key Messages
[13:40:53] Finished 'veeva-deploy' after 22 ms

Nothing get sent to my account, I validated using FTP. I tried adding command line option -V for verbosity, didn't change.

Thanks,

**Comment by YannickGagnon** [comment]
I realized I needed to run 'gulp stage' before running 'gulp veeva-deploy'
But running gulp stage gives me the following:

[13:53:15] Using gulpfile ~/Sites/Company/project/gulpfile.js
[13:53:16] Starting 'clean:deploy'...
[13:53:16] Starting 'clean'...
[13:53:16] Finished 'clean:deploy' after 8.16 ms
[13:53:16] Finished 'clean' after 56 ms
[13:53:16] Starting 'build'...
[13:53:17] all files 23.84 kB
[13:53:17] Starting 'veeva-module:js-build'...
NOTE ⤷ Processing Veeva JS dependencies.
[13:53:17] head.load.min.js 4.53 kB
NOTE ⤷ Main Scripts
[13:53:18] main.js 22.89 kB
NOTE ⤷ Vendor Scripts - Build Mode
[13:53:20] vendor.js 199.6 kB
NOTE ⤷ Copying Veeva JS dependencies to project
[13:53:20] js/head.load.min.js 4.53 kB
[13:53:20] js/main.js 22.89 kB
[13:53:20] js/vendor.js 199.6 kB
[13:53:20] all files 227.02 kB
✔︎  Done Processing Veeva JS dependencies.
[13:53:20] Finished 'veeva-module:js-build' after 2.79 s
[13:53:20] Starting 'assemble'...
NOTE ⤷ Assembling Key Messages
NOTE ⤷ Copying Key Message Assets
NOTE ⤷ Generating Global app.json file
NOTE ⤷ Generating sitemap.json file
WARNING ⤷ Skipping generateSitemapFile: Key Message Sitemap does not exist
NOTE ⤷ Copying Global Assets to Key Messages
✔︎ Done Assembling Key Messages
[13:53:21] Finished 'assemble' after 1.11 s
[13:53:21] Starting 'veeva-thumbs'...
NOTE ⤷ Generating Veeva Thumbnails
info: TypeError: undefined is not an object (evaluating '$slidesConfigured[i].noSwipeZone')
info: 
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1 in Section
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1 in pageChanged
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:6 in n
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in dispatch
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in a
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:4
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:4 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1 in start
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/main.js?v=1:1 in success
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in h
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:3 in fireWith
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:5 in i
info:   file:///Users/Me/Sites/Company/project/build/veeva-home/global/js/vendor.js?v=1:5 in i
info: TypeError: undefined is not an object (evaluating '$slidesConfigured[i].noSwipeZone')
info: 
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1 in Section
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1 in pageChanged
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:6 in n
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in dispatch
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in a
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:4
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:4 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1 in start
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/main.js?v=1:1 in success
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in h
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:3 in fireWith
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:5 in i
info:   file:///Users/Me/Sites/Company/project/build/veeva-overview/global/js/vendor.js?v=1:5 in i
info: TypeError: undefined is not an object (evaluating '$slidesConfigured[i].noSwipeZone')
info: 
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1 in Section
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1 in pageChanged
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:6 in n
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in dispatch
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in a
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:4
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:4 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1 in start
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/main.js?v=1:1 in success
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in h
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:3 in fireWith
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:5 in i
info:   file:///Users/Me/Sites/Company/project/build/veeva-resources/global/js/vendor.js?v=1:5 in i
info: TypeError: undefined is not an object (evaluating '$slidesConfigured[i].noSwipeZone')
info: 
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1 in Section
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1 in pageChanged
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:6 in n
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in dispatch
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in a
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:4
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:2 in each
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:4 in trigger
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1 in start
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/main.js?v=1:1 in success
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in h
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:3 in fireWith
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:5 in i
info:   file:///Users/Me/Sites/Company/project/build/veeva-sitemap/global/js/vendor.js?v=1:5 in i

**Comment by stevebritton** [comment]
Hi YannickGagnon,

It looks like the process that creates the screenshots is bombing out. By chance, did you install the following dependency?

**imagemagick**

If not, there's some info on the project's ReadMe regarding the imagemagick dependency.

**Comment by YannickGagnon** [comment]
Well, when I run gulp build, everything gets compiled in the build directory and images as well, even though the generated thumbnails are named page.png and the templates refers to them as page-thumb.jpg.
