### ISSUE TITLE
Gulp task stops without throwing an error

### ISSUE THREAD

**Issue by AntonyMayer** [devopsgroup-io/veeva#38]
After cloning repo and running npm installation both in root and "veeva/examples/clm/" I was trying to run default gulp task. For some reason gulp quits without throwing any error to console. Imagemagick installed. No errors thrown during npm install process. The only file i modified is veeva/package.json - changed "name" (otherwise it was throwing an error "Can't install veeva as dependency of veeva"). 

Below is my output:

```
$ gulp

   ✔︎ configuration.yml file exists
   ✔︎ Product name
   ✔︎ Primary CLM presentation name
   ✔︎ Assets CLM presentation name 

[15:18:55] Using gulpfile ~/aside/custom_veeva/gulpfile.js
[15:18:56] Starting 'assemble'...
 NOTE ⤷ Assembling Key Messages
[15:18:56] Starting 'sass:dev'...
[15:18:56] Starting 'scripts:dev'...
[15:18:56] Starting 'veeva-module:js-build'...
 NOTE ⤷ Processing Veeva JS dependencies.
[15:18:56] Starting 'images:dev'...

$

$ veeva -v
v0.27.0

$ gulp -v
[15:19:44] CLI version 3.9.1
[15:19:44] Local version 3.9.1

$ node -v
v6.10.0

$ npm -v
3.10.10
```

I would appreciate any advice.

**Comment by stevebritton** [comment]
Hi @AntonyMayer,

Quick question - are you using the sample **configuration.yml** file, or have you made any changes?

I ask because I've identified a few instances where errors related to the formatting of the  **configuration.yml** were occurring, but not reporting. I'm in the process of working through a new release that will resolve this issue.

Please let me know when you have a moment.

Thanks,
Steve

**Comment by AntonyMayer** [comment]
Hi @stevebritton ,
Thank you for reply. I'm using sample configuration.yml file located at "veeva/examples/clm/" without any modifications.

**Comment by stevebritton** [comment]
Hi @AntonyMayer,

A new version has been released, which includes some validation for the configuration.yml file as well as node packages. Also, please note that the new version of PhantomJS now requires node version >=6.0.

-Steve

**Comment by AntonyMayer** [comment]
Thank you, works perfect!

**Comment by romellem** [comment]
FYI to anyone running into this problem, the process seeming to die at `Starting 'images:dev'...` is a bit of a red herring.

The problem actually is with the `sass:dev` gulp task.

You can verify by running `gulp sass:dev` and see it die out prematurely. 

To fix this, run

```
sudo gem install sass
```

Afterward, `gulp`, `gulp build`, etc. should run as intended.
